# Generated by Django 3.0.4 on 2020-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnea_demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(default='NO ANSWER!'),
        ),
    ]
