# Generated by Django 3.0.4 on 2020-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnea_demo_app', '0002_post_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='git_version',
            field=models.TextField(default='a1d3275554d67a5b4c7267e3279bbb40841326d7'),
        ),
    ]
